apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: myds
  name: myds
spec:
  selector:
    matchLabels:
      app: myds-pod
  template:
    metadata:
      labels:
        app: myds-pod
    spec:
      containers:
      - image: nginx:alpine
        name: nginx
