apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: myapprc
  name: myapprc
spec:
  replicas: 3
  selector:
      app: myapprc-pod
  template:
    metadata:
      labels:
        app: myapprc-pod
    spec:
      containers:
      - image: nginx:alpine
        name: nginx
